# created initial config template with:
#
#    benthos create stdin/command/stdout > config.yaml
#
# then removed a bunch of stuff i don't think i'll be interested in

http:
  enabled: false
input:
  label: ""
  stdin:
    codec: lines
    max_buffer: 1000000
pipeline:
  threads: -1
  processors:

    # https://www.benthos.dev/docs/components/processors/command
    - label: "sketchy_echo"
      command:
        name: "sh"
        args_mapping: '[ "-c", "scripts/sketchy-echo.sh" ]'

    # https://www.benthos.dev/docs/components/processors/catch
    - catch:
      - command:
          name: "sh"
          args_mapping: '[ "-c", "scripts/report-error.sh" ]'
output:
  label: ""
  stdout:
    codec: lines
logger:
  level: INFO
  format: logfmt
  add_timestamp: false
  level_name: level
  timestamp_name: time
  message_name: msg
  static_fields:
    '@service': benthos
  file:
    path: ""
    rotate: false
    rotate_max_age_days: 0
